// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace api1.Models
{
    public partial class Course : IValidatableObject
    {
        public Course()
        {
            CourseInstructor = new HashSet<CourseInstructor>();
            Enrollment = new HashSet<Enrollment>();
        }

        public int CourseId { get; set; }
        [Required(ErrorMessage = "請輸入課程名稱")]
        [StringLength(20, ErrorMessage = "課程名稱不得大於 20 個字元")]
        public string Title { get; set; }

        [Required]
        [Range(1, 5, ErrorMessage = "請設定 1 ~ 5")]
        public int Credits { get; set; }

        public int DepartmentId { get; set; }

        public virtual Department Department { get; set; }
        public virtual ICollection<CourseInstructor> CourseInstructor { get; set; }
        public virtual ICollection<Enrollment> Enrollment { get; set; }

        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        {
            if (Credits >= 3 && !this.Title.Contains("優"))
            {
                yield return new ValidationResult("評價大於 3 個課程，請在課程名稱上加入[優]字樣", new string[] { "Title" });
            }
        }
    }
}